---

- name: k8s-node Deploying
  gather_facts: yes
  hosts: single
  become: yes
  tasks:
    - name: Install containerd
      apt:
        name: containerd
        state: latest
    - name: Create a directory containerd
      file:
        path: /etc/containerd
        state: directory
    - name: copy config to directory
      ansible.builtin.get_url:
        url: config.toml
        dest: /etc/containerd
    - name: Restart Containerd
      service:
        name: containerd
        state: restarted
    - name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
      shell: swapoff -a
      become: true
    - name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'
    - name: Enable bridging
      ansible.builtin.command: "sudo sed -ie 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g' /etc/sysctl.conf"
    - name: Touch k8s.conf
      file:
        path: /etc/modules-load.d/k8s.conf
        state: touch
    - name: Change k8s.conf
      lineinfile:
        path: /etc/modules-load.d/k8s.conf
        insertafter: EOF
        line: 'br_netfilter'
      become: true
    - name: Restart host
      shell: "sudo shutdown -r now"
      async: 1
      poll: 0
      become: true
    - name: Wait for server to restart
      wait_for_connection:
        timeout: 120
        delay: 10
    - name: add key gpg
      shell: curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg
      become: true
    - name: add package
      shell: echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
    - name: Run apt get update
      apt:
        update_cache: yes
    - name: Update all packages to the last version
      apt:
        upgrade: dist
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
    - name: Install k8s packages
      apt:
        name: 
          - kubeadm 
          - kubectl 
          - kubelet
        state: present
      become: yes
